# Generated by Django 4.1.7 on 2023-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipitationMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(verbose_name='Широта')),
                ('longitude', models.IntegerField(verbose_name='Долгота')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('mm_h', models.IntegerField(verbose_name='ММ/Ч')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
