# Generated by Django 4.1.7 on 2023-06-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_precipitationmeasurement_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='main.precipitationmeasurement')),
                ('latitude', models.IntegerField(verbose_name='Широта')),
                ('longitude', models.IntegerField(verbose_name='Долгота')),
                ('sea_height', models.IntegerField(verbose_name='Высота над уровнем моря')),
                ('area', models.IntegerField(verbose_name='Площадь')),
            ],
        ),
    ]
