# Generated by Django 4.1.7 on 2023-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Автор')),
                ('type', models.IntegerField(verbose_name='Тип')),
                ('measurement', models.ManyToManyField(to='main.precipitationmeasurement')),
            ],
        ),
    ]
