# Generated by Django 4.1.7 on 2023-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_measurementsensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsensors',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
