# Generated by Django 4.1.7 on 2023-06-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_measurementsensors_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipitationForCountry',
            fields=[
                ('min', models.IntegerField(verbose_name='Минимум')),
                ('max', models.IntegerField(verbose_name='Максимум')),
                ('avg', models.IntegerField(verbose_name='Среднее')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='main.country')),
            ],
        ),
    ]
